# Generated by Django 2.2 on 2022-10-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_auto_20221020_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='municipality',
            field=models.CharField(default='Florianopolis', max_length=255, verbose_name='Municipality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(default='Fazenda Default', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='state',
            field=models.CharField(default='Santa Catarina', max_length=255, verbose_name='State'),
            preserve_default=False,
        ),
    ]
